name: Lint

on: [push]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint code
      run: |
        npm install
        npm install eslint
        ./node_modules/.bin/eslint .