name: Lint

on: [push]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint code
      run: |
        rm -rf node_modules
        npm install --force
        ./node_modules/.bin/eslint src -c .eslintrc