name: Tests

on: [push]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      run: |
        rm -rf node_modules
        npm install --force
        npm test